image: php:7.0-cli

cache:
  paths:
    - ./vendor

stages:
  - test
  - publish

before_script:
    - apt-get update -y
    - apt-get install wget git -y
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"

test:
    stage: test
    script:
        - php composer.phar install -o
        - cp phpunit.xml.dist phpunit.xml
        - vendor/bin/phpunit --coverage-text --colors=never --debug
    tags:
        - test
