image: php:7.0-cli

cache:
  paths:
    - ./vendor

stages:
  - test
  - publish

test:
    stage: test
    before_script:
        - apt-get update -y
        - apt-get install wget git -y
        - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
        - pecl install xdebug-2.5.0
        - docker-php-ext-enable xdebug
    script:
        - php composer.phar install -o
        - php vendor/bin/php-cs-fixer fix --dry-run --config ./.php_cs.dist.php -vv

        - cp phpunit.xml.dist phpunit.xml
        - vendor/bin/phpunit --coverage-text --colors=never
    tags:
        - test

publish:
    stage: publish
    before_script:
        - apt-get update -y
        - apt-get install git -y
    script:
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$DEPLOYMENT_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - echo $CI_COMMIT_REF_NAME
        - git push git@github.com:MikeTralala/cron-expression.git $CI_COMMIT_REF_NAME
    tags:
        - publish
