image: php:7.0-cli

cache:
  paths:
    - ./vendor

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - composer install -o
  tags:
    - build

test:
  stage: test
  script:
    - cp phpunit.xml.dist phpunit.xml
    - vendor/bin/phpunit --coverage-text --colors=never --debug
  tags:
    - test
